export const States = {
  DISARMED: 'DISARMED',
  DISARMED_DOOR_OPEN: 'DISARMED_DOOR_OPEN',
  ARMED: 'ARMED',
  ARMED_DOOR_OPEN: 'ARMED_DOOR_OPEN',
  ARMED_WARNING: 'ARMED_WARNING',
  ARMED_ALARM: 'ARMED_ALARM',
};
